version: '3'
services:
  app:
    build: .
    container_name: backend
    ports:
      - "3000:3000"   # Mapeando a porta 3000 do container para a porta 3000 da máquina host
    volumes:
      - .:/usr/src/app   # Mapeando o diretório atual para dentro do container (útil para desenvolvimento)
    environment:
      - NODE_ENV=production
    depends_on:
      - db  # Garantir que o serviço de banco de dados esteja rodando antes do app

  db:
    image: mysql:5.7   # Usando a imagem oficial do MySQL
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: funcionarios_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
